version: "3.9"
services:
  db :
    image: mysql
    ports:
      - "8001:3306"
  backend :
    image: spring-security
    build: https://github.com/Fedich09/spring-security.git
    ports:
      - "8000:8080"
